import os
import glob
import pandas as pd
import fnmatch
import argparse

parser = argparse.ArgumentParser(description="Merges Excel files generated by the Telangana scraper.")
args = parser.parse_args()

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_DIR = os.path.join(BASE_DIR, "TS")
statename="TELANGANA OUTPUT"
print(OUTPUT_DIR)
file_prefix="page_"
filenames = [os.path.join(OUTPUT_DIR, filename) 
             for filename in os.listdir(OUTPUT_DIR) 
             if fnmatch.fnmatch(filename, f"{file_prefix}*.xlsx")]
dataframes=[]
# filenames=glob.glob(OUTPUT_DIR + f"{file_prefix}.xlsx")
for file_path in filenames:
    df=pd.read_excel(file_path)
    dataframes.append(df)
merged_df=pd.concat(dataframes,ignore_index=True)
output_excel_file=os.path.join(OUTPUT_DIR,f"{statename}.xlsx")
merged_df.to_excel(output_excel_file,index=False)
print("merged excel file saved at:",output_excel_file)